version: "3.8"
services:
  db:
    image: postgres:15
    container_name: library_db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - library-net
  app:
    build: .
    container_name: library_app
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: library
      DB_USER: postgres
      DB_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 20
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SERVER_PORT: 8080
    networks:
      - library-net
volumes:
  pgdata:
networks:
  library-net:
    driver: bridge
