spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:library}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  hikari:
    maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
    minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    root: INFO
    com.example.library: DEBUG
